version: '3.1'

services:
  db:
    image: 'mysql:8.0.28'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_usuarios
    container_name: spring-mysql
    ports:
      - "3306:3306"