version: '3.1'

services:
  mysql:
    image: 'mysql:8.0.28'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_usuarios
    container_name: spring-mysql
    ports:
      - "3306:3306"

  postgresql:
    image: 'postgres:14.3'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msvc_cursos
    container_name: spring-postgresql